# Generated by Django 4.2.5 on 2023-09-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensity', models.IntegerField()),
                ('sector', models.TextField(max_length=50)),
                ('topic', models.TextField(max_length=50)),
                ('insight', models.TextField()),
                ('url', models.URLField()),
                ('region', models.TextField(max_length=50)),
                ('startYear', models.DateField(verbose_name='Year')),
                ('impact', models.TextField()),
                ('added', models.DateTimeField()),
                ('published', models.DateTimeField()),
                ('country', models.TextField()),
                ('relevance', models.IntegerField()),
                ('pestle', models.TextField()),
                ('source', models.TextField()),
                ('title', models.TextField()),
                ('likelihood', models.IntegerField()),
            ],
        ),
    ]
