# Generated by Django 4.2.5 on 2023-09-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='startYear',
        ),
        migrations.AddField(
            model_name='news',
            name='end_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='start_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='added',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='impact',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='insight',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='pestle',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='region',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='sector',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='topic',
            field=models.CharField(max_length=255),
        ),
    ]
