# Generated by Django 4.2.5 on 2023-09-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_news_startyear_news_end_year_news_start_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='end_year',
            field=models.TextField(max_length=4),
        ),
        migrations.AlterField(
            model_name='news',
            name='pestle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='start_year',
            field=models.TextField(max_length=4),
        ),
    ]
